import { parseCatalogLines } from '../src/features/products/lib/parseCatalogLines'

// This is the actual raw text PDF.js extracted from the user's real PDF
// file (captured via the app's own diagnostic "Extracted text" view) —
// as opposed to the earlier test, which used text the user copy-pasted
// by hand from a PDF viewer. The two differ in an important way: this
// real extraction has only 2 numbers per data line (buying, selling) —
// no wholesale price, no date — which the parser has to handle too.
const RAW_EXTRACTION = `PRODUCT CATALOG
FILTER BY : OVERVIEW
CREATED ON : 16/08/2026 11:26 pm
GENERATED BY : Lucy
DESCRIPTION MEASUREMENT BUYING PRICE RETAIL PRICE
BRAIDS
JIBAMBE LONG
(1/350)
pcs 40 70
JIBAMBE LONG(1/
BLUE)
pcs 40 70
99J LONG AVIS pcs 57 80
99J LONG JIBAMBE pcs 40 70
AVIS (900) LONG pcs 72 80
AMARA BRAID pcs 200 250
CLEANSER
FACIAL CLEANSER pcs 180 300
DR. RASHEL
CLENSER
pcs 220 400`

const lines = RAW_EXTRACTION.split('\n')
const rows = parseCatalogLines(lines)

console.log(`Parsed ${rows.length} products from the real raw extraction format\n`)
for (const row of rows) {
  console.log(`${String(row.rowNumber).padStart(2)}. [${row.category ?? '—'}] ${row.name}  —  buy ${row.buyingPrice}, sell ${row.sellingPrice}`)
}

const checks: [string, boolean][] = [
  ['Parsed 8 products', rows.length === 8],
  ['No leftover metadata lines as products', !rows.some((r) => r.name?.includes('FILTER BY') || r.name?.includes('CREATED ON'))],
  ['No "PRODUCT CATALOG" title leaking into a name', !rows.some((r) => r.name?.includes('PRODUCT CATALOG'))],
  ['Wrapped "JIBAMBE LONG (1/350)" reconstructed', rows.some((r) => r.name === 'JIBAMBE LONG (1/350)')],
  ['Single-line "99J LONG AVIS" correct', rows.some((r) => r.name === '99J LONG AVIS' && r.buyingPrice === 57 && r.sellingPrice === 80)],
  ['"AMARA BRAID" correct prices', rows.some((r) => r.name === 'AMARA BRAID' && r.buyingPrice === 200 && r.sellingPrice === 250)],
  ['"FACIAL CLEANSER" tagged Cleanser category', rows.some((r) => r.name === 'FACIAL CLEANSER' && r.category === 'CLEANSER')],
  ['No NaN prices', rows.every((r) => Number.isFinite(r.buyingPrice) && Number.isFinite(r.sellingPrice))],
]

console.log('\n--- Checks ---')
let allPassed = true
for (const [label, passed] of checks) {
  console.log(`${passed ? '✅' : '❌'} ${label}`)
  if (!passed) allPassed = false
}
console.log(allPassed ? '\nAll checks passed.' : '\nSOME CHECKS FAILED.')
