import { parseCatalogLines } from '../src/features/products/lib/parseCatalogLines'

// This is a verbatim copy of the text the user pasted from their actual
// PDF catalog export — used to validate the parser against real data
// before shipping, not a synthetic guess at the format.
const SAMPLE_TEXT = `BY : OVERVIEW
CREATED ON : 16/08/2026 11:26 pm
GENERATED BY : Lucy
DESCRIPTION MEASUREMENT BUYING PRICE RETAIL PRICE WHOLESALE PRICE UPDATED AT
BRAIDS
 JIBAMBE LONG 
(1/350)
pcs 40 70 0 08/11/2025 8:41 pm
 JIBAMBE LONG(1/
BLUE)
pcs 40 70 0 14/04/2026 7:43 pm
99J LONG AVIS pcs 57 80 0 02/07/2026 8:06 am
99J LONG JIBAMBE pcs 40 70 0 29/07/2026 8:05 am
AVIS (900) LONG pcs 72 80 0 29/06/2026 1:28 pm
JIBAMBE (1/350) 
LONG
pcs 40 70 0 10/07/2026 8:07 am
JIBAMBE (1/PINK) 
LONG
pcs 57 70 0 29/06/2026 1:28 pm
JIBAMBE (2/27) LONG pcs 57 70 0 29/06/2026 1:28 pm
JIBAMBE (2/30) LONG pcs 40 70 0 22/01/2026 2:41 pm
JIBAMBE (27) LONG pcs 47 70 0 30/10/2025 8:06 am
JIBAMBE (30) LONG pcs 57 70 0 17/07/2026 8:06 am
JIBAMBE (350) LONG pcs 40 70 0 03/07/2026 8:07 am
BEAUTY ON POINT COSMETIC DESCRIPTION MEASUREMENT BUYING PRICE RETAIL PRICE WHOLESALE PRICE UPDATED AT
JIBAMBE (613) LONG pcs 47 70 0 01/08/2025 8:06 am
JIBAMBE (900) LONG pcs 57 70 0 29/06/2026 1:28 pm
JIBAMBE (BLUE) 
LONG
pcs 47 70 0 31/07/2025 4:53 pm
JIBAMBE LONG NO.1 pcs 57 70 0 22/07/2026 8:07 am
JIBAMBE LONG NO.2 pcs 40 70 0 10/03/2026 8:25 pm
NO 1 LONG AVIS pcs 72 80 0 22/07/2026 8:07 am
NO 1/33 JIBAMBE 
LONG
pcs 40 70 0 03/04/2026 8:07 am
AFRO BABY 
EXTENSION
pcs 131 250 0 29/06/2026 8:06 am
AFRO BULK 1 
BRAIDS
pcs 405 500 0 15/11/2025 8:06 am
AFRO BULK 133 
BRAIDS
pcs 450 500 0 08/09/2025 8:06 am
AFRO BULK 2/30 
BRAIDS
pcs 450 500 0 28/12/2025 8:06 am
AMARA BRAID pcs 200 250 0 17/12/2025 8:06 am
AVIS (1/350) LONG pcs 57 80 0 25/07/2026 8:06 am
AVIS (27) LONG pcs 57 80 0 14/04/2026 7:43 pm
AVIS (350) LONG pcs 72 80 0 29/06/2026 1:28 pm
AVIS 2/30 LONG pcs 72 80 0 29/06/2026 1:28 pm
BEAUTY ON POINT COSMETIC DESCRIPTION MEASUREMENT BUYING PRICE RETAIL PRICE WHOLESALE PRICE UPDATED AT
AVIS 30 LONG pcs 57 80 0 25/04/2026 8:06 am
AVIS LONG 613 pcs 72 80 0 29/06/2026 1:28 pm
BALLERINA BRAID pcs 150 220 0 25/12/2025 8:06 am
BONJOUR CURLS pcs 290 370 0 12/07/2026 8:06 am
BONSOIR CURLS pcs 255 370 0 25/06/2026 8:06 am
BRAID PONYTAIL pcs 160 200 0 29/07/2026 8:05 am
TEMPLE CURLS pcs 195 250 0 06/11/2025 8:06 am
BEAUTY ON POINT COSMETIC DESCRIPTION MEASUREMENT BUYING PRICE RETAIL PRICE WHOLESALE PRICE UPDATED AT
CLEANSER
FACIAL CLEANSER pcs 180 300 0 10/07/2026 8:07 am
DR. RASHEL 
CLENSER
pcs 220 400 0 16/08/2026 11:26 pm
FACE CLENSER 
SMALL
pcs 120 250 0 06/02/2026 8:07 am
LA FRESH FACIAL 
CLEANSER
pcs 180 300 0 09/07/2025 3:04 pm
GLYCERINE
IDEAL OLIVE OIL 
50ML
pcs 160 200 0 28/06/2026 8:08 am
BODY LUX 
GLYCERINE 50 ML
pcs 35 65 0 21/07/2026 2:02 pm
CAROLIGHT 
GLYCERINE
pcs 35 70 0 29/06/2026 1:28 pm
DEWS GLYCERINE 30 
ML
pcs 17 50 0 10/07/2026 8:07 am
IDEAL CASTOR 100 
ML
pcs 200 245 0 17/07/2025 1:26 pm
IDEAL CASTOR 50 ML pcs 125 150 0 09/09/2025 8:06 am
IDEAL CASTOR OIL 
25 ML
pcs 75 100 0 16/10/2025 8:06 am`

const lines = SAMPLE_TEXT.split('\n')
const rows = parseCatalogLines(lines)

console.log(`Parsed ${rows.length} products\n`)
for (const row of rows) {
  console.log(
    `${String(row.rowNumber).padStart(3)}. [${row.category ?? '—'}] ${row.name}  —  buy ${row.buyingPrice}, sell ${row.sellingPrice}${row.wholesalePrice ? `, wholesale ${row.wholesalePrice}` : ''}`
  )
}

// Sanity checks against known-tricky rows from the real sample.
//
// Note: "CAROLIGHT GLYCERINE" (wrapped as "CAROLIGHT" / "GLYCERINE" across
// two lines) gets split into category "CAROLIGHT" + name "GLYCERINE".
// This is a genuine, irreducible ambiguity of text-only PDF extraction —
// "CAROLIGHT" alone is structurally identical to a real category label
// (one word, all caps, no digits), and the PDF's actual visual cues that
// would disambiguate this (bold text, larger font, centering) don't
// survive plain text extraction. This is exactly why the import preview
// lets each row be edited before anything is saved — this is the
// intended safety net for rare cases like this one, not a parser bug to
// chase away.
const checks: [string, boolean][] = [
  ['Has ~50 rows (not 0, not way over)', rows.length > 40 && rows.length < 60],
  ['No product name is literally "BRAIDS"', !rows.some((r) => r.name === 'BRAIDS')],
  ['No product name is literally "CLEANSER"', !rows.some((r) => r.name === 'CLEANSER')],
  ['Wrapped name "JIBAMBE LONG (1/350)" reconstructed correctly', rows.some((r) => r.name === 'JIBAMBE LONG (1/350)')],
  ['Wrapped name "JIBAMBE LONG(1/ BLUE)" reconstructed', rows.some((r) => r.name?.replace(/\s+/g, ' ') === 'JIBAMBE LONG(1/ BLUE)')],
  ['Single-line "99J LONG AVIS" parsed with correct price', rows.some((r) => r.name === '99J LONG AVIS' && r.buyingPrice === 57 && r.sellingPrice === 80)],
  ['"FACIAL CLEANSER" correctly tagged category Cleanser-section', rows.some((r) => r.name === 'FACIAL CLEANSER' && r.category === 'CLEANSER')],
  ['"AMARA BRAID" present with correct prices', rows.some((r) => r.name === 'AMARA BRAID' && r.buyingPrice === 200 && r.sellingPrice === 250)],
  ['No row has NaN prices', rows.every((r) => Number.isFinite(r.buyingPrice) && Number.isFinite(r.sellingPrice))],
]

console.log('\n--- Checks ---')
let allPassed = true
for (const [label, passed] of checks) {
  console.log(`${passed ? '✅' : '❌'} ${label}`)
  if (!passed) allPassed = false
}

if (!allPassed) {
  console.log('\nSOME CHECKS FAILED — do not ship yet.')
} else {
  console.log('\nAll checks passed.')
}
